### ISSUE TITLE
Ethereum transaction builder

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/wagyu#30]
### Summary
- Implement Ethereum transaction builder
- Implement test suite for Ethereum transaction builder

**Comment by gakonst** [comment]
Can probably use [this](https://github.com/synlestidae/ethereum-tx-sign/blob/master/src/raw_transaction.rs) as a starting point. [rust-web3](https://github.com/tomusdrw/rust-web3) does not support signing transactions without the `eth_sign` endpoint of a node unfortunately

**Comment by raychu86** [comment]
Thanks for the heads up! We currently have a preliminary implementation for generating Ethereum transactions in [feature/transactions](https://github.com/ArgusHQ/wagyu/blob/feature/transactions/ethereum/src/transaction.rs).

**Comment by vhnatyk** [comment]
> Thanks for the heads up! We currently have a preliminary implementation for generating Ethereum transactions in [feature/transactions](https://github.com/ArgusHQ/wagyu/blob/feature/transactions/ethereum/src/transaction.rs).

@raychu86  - can you check #85? Wanted to play with your crate **and** Ethereum transactions
