### ISSUE TITLE
#![no_std] support

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/wagyu#44]
Tracking thread to determine how to incorporate `#![no_std]` (if at all) into `wagyu`.

**Comment by vhnatyk** [comment]
Hi - sorry to bug, but wagu or wagyu?)

> Tracking thread to determine how to incorporate `#![no_std]` (if at all) into `wagu`.

**Comment by howardwu** [comment]
No worries and thanks for catching that. Changed to `wagyu` (`wagu` was its former name)

**Comment by howardwu** [comment]
#178
